---
- name: Install default packages on Ubuntu 22.04
  hosts: all
  become: yes
  ignore_unreachable: yes
  gather_facts: yes

  vars:
    default_packages:
      - curl
      - chrony
      - wget
      - git
      - vim
      - nano
      - unzip
      - zip
      - htop
      - tree
      - software-properties-common
      - lsb-release
      - net-tools
      - openssh-client
      - openssh-server
      - build-essential
      - python3-pip
      - python3-venv
      - default-jdk
      - sysstat
      - dstat

  tasks:
    - name: Update apt package cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install default packages
      ansible.builtin.apt:
        name: "{{ default_packages }}"
        state: present
        update_cache: yes

#- hosts: "{{ group }}"
#
#  become: yes
#  ignore_unreachable: yes
#  gather_facts: yes
#  tasks:
#
#  - name: install core packages
#    apt:
#      name:
#        - prometheus-node-exporter
#        - nfs-common
#        - open-vm-tools
#        - unzip
#        - zip
#      update_cache: yes


